<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-07T13:21:26 IST" name="AuraAutomationSuite" finished-at="2024-04-07T13:22:07 IST" duration-ms="40935">
    <groups>
      <group name="regression">
        <method signature="TC002_ScheduleAppointmentTest.test_Validate_ScheduleAppointment()[pri:0, instance:testcases.TC002_ScheduleAppointmentTest@71b1176b]" name="test_Validate_ScheduleAppointment" class="testcases.TC002_ScheduleAppointmentTest"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TC001_LoginValidationTest.test_Validate_LoginTest()[pri:0, instance:testcases.TC001_LoginValidationTest@4e91d63f]" name="test_Validate_LoginTest" class="testcases.TC001_LoginValidationTest"/>
      </group> <!-- sanity -->
      <group name="master">
        <method signature="TC001_LoginValidationTest.test_Validate_LoginTest()[pri:0, instance:testcases.TC001_LoginValidationTest@4e91d63f]" name="test_Validate_LoginTest" class="testcases.TC001_LoginValidationTest"/>
        <method signature="TC002_ScheduleAppointmentTest.test_Validate_ScheduleAppointment()[pri:0, instance:testcases.TC002_ScheduleAppointmentTest@71b1176b]" name="test_Validate_ScheduleAppointment" class="testcases.TC002_ScheduleAppointmentTest"/>
      </group> <!-- master -->
    </groups>
    <test started-at="2024-04-07T13:21:26 IST" name="Login Test" finished-at="2024-04-07T13:22:07 IST" duration-ms="40935">
      <class name="testcases.TC001_LoginValidationTest">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testcases.TC001_LoginValidationTest@4e91d63f]" started-at="2024-04-07T13:21:26 IST" name="setup" finished-at="2024-04-07T13:21:35 IST" duration-ms="8211" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_Validate_LoginTest()[pri:0, instance:testcases.TC001_LoginValidationTest@4e91d63f]" started-at="2024-04-07T13:21:35 IST" name="test_Validate_LoginTest" finished-at="2024-04-07T13:21:56 IST" duration-ms="21923" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed while validating Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed while validating Login expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at testcases.TC001_LoginValidationTest.test_Validate_LoginTest(TC001_LoginValidationTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Validate_LoginTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.TC001_LoginValidationTest@4e91d63f]" started-at="2024-04-07T13:21:57 IST" name="teardown" finished-at="2024-04-07T13:21:57 IST" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.TC001_LoginValidationTest -->
      <class name="testcases.TC002_ScheduleAppointmentTest">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testcases.TC002_ScheduleAppointmentTest@71b1176b]" started-at="2024-04-07T13:21:57 IST" name="setup" finished-at="2024-04-07T13:22:03 IST" duration-ms="6483" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_Validate_ScheduleAppointment()[pri:0, instance:testcases.TC002_ScheduleAppointmentTest@71b1176b]" started-at="2024-04-07T13:22:03 IST" name="test_Validate_ScheduleAppointment" finished-at="2024-04-07T13:22:06 IST" duration-ms="2889" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed while validating the appointment creation expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed while validating the appointment creation expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at testcases.TC002_ScheduleAppointmentTest.test_Validate_ScheduleAppointment(TC002_ScheduleAppointmentTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Validate_ScheduleAppointment -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.TC002_ScheduleAppointmentTest@71b1176b]" started-at="2024-04-07T13:22:07 IST" name="teardown" finished-at="2024-04-07T13:22:07 IST" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.TC002_ScheduleAppointmentTest -->
    </test> <!-- Login Test -->
  </suite> <!-- AuraAutomationSuite -->
</testng-results>
